### PR TITLE
Fix #12 : don't download the asked version if it is already installed

### LINKED ISSUE #12: Don't reinstall versions which have already been installed?
How would you feel about making `psvm install v0.9.0` be a no-op if `v0.9.0` already exists on the system? This makes it easier for scripts using `psvm`, as then they don't have to check for themselves.

### PR DESCRIPTION
**Pull request by ThomasCrevoisier**

### CODE REVIEW

**Comment by ThomasCrevoisier** [comment]
@hdgarrood Do you see something else to add ?

**Comment by hdgarrood** [comment]
Not really related to this PR but psvm should exit with a nonzero code if the requested version could not be installed, using `process.exit`.

**Comment by ThomasCrevoisier** [comment]
@hdgarrood Yep, you right. Just wondering, are there any convention for exit codes ? Or could we just exit with a code `1` ?

**Comment by hdgarrood** [comment]
I'm not aware of any convention; I'd personally go with 1.

**Comment by ThomasCrevoisier** [comment]
@hdgarrood Just added the error handling + exit process for this feature.

**Comment by hdgarrood** [comment]
Looks good!

**Pull request merged**
