### PR TITLE
9 fix psvm current

### PR DESCRIPTION
**Pull request by ThomasCrevoisier**
@SiegfriedEhret What do you think about this message ? Do you think it's helpful enough or could be improved ?

### CODE REVIEW

**Comment by hdgarrood** [comment]
The message looks great, although the grammar can be improved a little. I think I'd write:

> No versions of psc are installed.
> You can install the latest version by running : psvm install-latest
> List all the installed versions by running : psvm ls
> Select a version after installing by it running : psvm use <VERSION>

I would also recommend printing the error message to standard error by using `console.error`, and exiting with a nonzero exit code, so that if people are using psvm in a script, it's easier to handle this case.

**Comment by SiegfriedEhret** [comment]
:+1: super cool guys, it will be really helpful !

**Comment by ThomasCrevoisier** [comment]
@hdgarrood Yep, you're right. I modified this. If it looks ok for everyone, I'll merge ^^

**Comment by hdgarrood** [comment]
Looks good to me :+1:

**Pull request merged**
