### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by hdgarrood**
This seems to work on Pulp's Windows CI (which uses Appveyor); you can see it in action here: https://ci.appveyor.com/project/bodil/pulp

### CODE REVIEW

**Comment by ThomasCrevoisier** [comment]
Nice :)
Maybe we can update the README to specify it could be used on Mac/Linux and Windows ?

**Comment by hdgarrood** [comment]
Ah yes, of course

**Comment by hdgarrood** [comment]
Fixes #26!

**Comment by ThomasCrevoisier** [comment]
Great ! Thanks a lot :)

**Comment by hdgarrood** [comment]
Do you think it might make sense to publish a release to npm with these changes?

**Comment by ThomasCrevoisier** [comment]
Yep absolutely, I will do this in the afternoon.

**Comment by hdgarrood** [comment]
Wonderful, thank you!

**Pull request merged**
