### PR TITLE
Added support for psc-ide executables

### PR DESCRIPTION
**Pull request by doppioslash**
As per issue #7 , this commit fixes that.

### CODE REVIEW

**Comment by ThomasCrevoisier** [comment]
@doppioslash Great 😃  Have you tried installation on older version of purescript ? Just wondering if this work when `psc-ide` etc... are not present.

**Comment by doppioslash** [comment]
Ah, true, didn't think about that ^^;
I'll handle that case and update this.

**Comment by doppioslash** [comment]
@ThomasCrvsr any preference for how these errors should be handled? I'm not really a node.js person so not sure of best practices in this case. Also your code is nice and I wouldn't want to write a wart on it :P
It looks like there should either be a sanctioned way in bluebird to handle errors in an array of promises but I don't have time to read up on it, or I should get them out of the array.

**Comment by ThomasCrevoisier** [comment]
@doppioslash No worry, my code is far from perfect :)

Maybe we can use something like [glob](https://www.npmjs.com/package/glob) and use a pattern like `**/psc*` and then perform the copy + permission change, what do you think ? :)

Otherwise, you can pass a second argument to `.then()` which is the error callback.

We could write something like :

```
util.copy(path.join(srcPath, 'psc-docs'), path.join(destPath, 'psc-docs'))
.then(/* performing the permission changes */, /* handle possible error*/)
```

**Comment by ThomasCrevoisier** [comment]
@doppioslash Need some help ? :) I just thought that maybe we can merge it as it is now and fix the support of old versions just after.

**Comment by doppioslash** [comment]
Hi, sorry been busy, I got some half done version I need to go back to.

**Pull request merged**
